### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by EOOkuro**

### CODE REVIEW

**Comment by EOOkuro** [comment]
Usama front-end work.

**Review by EOOkuro — COMMENTED** [review]
Phone screen

**Review by EOOkuro — COMMENTED** [review]
Verification screen works, (add a back button in milestone 4)

**Review by EOOkuro — COMMENTED** [review]
Add your phone number

**Review by gerienesi — APPROVED** [review]
Phone number verification page

**Pull request merged**
